In [2]:
import numpy as np

In [10]:
x = np.array([1, 2, 3, 4])
y = np.array([5, 6, 7, 8])
print(x)
print(y)

[1 2 3 4]
[5 6 7 8]


In [4]:
print(x + y)
print(np.add(x, y))

[ 6  8 10 12]
[ 6  8 10 12]


In [5]:
print(x - y)
print(np.subtract(x, y))
print(x * y)
print(np.multiply(x, y))
print(x / y)
print(np.divide(x, y))

[-4 -4 -4 -4]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
[0.2        0.33333333 0.42857143 0.5       ]


In [13]:
print(x)
print(np.sqrt(x))
print(np.exp(x))
print(np.power(x, 2))

[1 2 3 4]
[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[ 1  4  9 16]


In [9]:
# broadcasting

X = np.array([1, 2, 3, 4]).reshape(2, 2)
Y = np.array([5, 6, 7, 8]).reshape(2, 2)

print(X - Y)
print(np.subtract(X, Y))
print(X * Y)
print(np.multiply(X, Y))
print(X / Y)
print(np.divide(X, Y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [15]:
print(X)
print('average of all: ', X.mean())
print('average of columns: ', X.mean(axis=0))
print('average of rows: ', X.mean(axis=1))

[[1 2]
 [3 4]]
average of all:  2.5
average of columns:  [2. 3.]
average of rows:  [1.5 3.5]


In [16]:
print('sum of all: ', X.sum())
print('sum of columns: ', X.sum(axis=0))
print('sum of rows: ', X.sum(axis=1))

sum of all:  10
sum of columns:  [4 6]
sum of rows:  [3 7]


In [17]:
X.std()

1.118033988749895

In [18]:
np.median(X)

2.5

In [19]:
X.max()

4

In [21]:
X.min()

1

In [22]:
print(3 + X)

[[4 5]
 [6 7]]


In [23]:
print(X - 3)

[[-2 -1]
 [ 0  1]]


In [24]:
print (X * 3)

[[ 3  6]
 [ 9 12]]


In [25]:
print(X / 3)

[[0.33333333 0.66666667]
 [1.         1.33333333]]


In [26]:
Y = np.arange(9).reshape(3, 3)
print(Y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
x = np.arange(3)
print(x)

[0 1 2]


In [30]:
print(Y + x)
# can the non-broadcasted array's shape
# be fit to reshaping it to the other? If so, np will broadcast it, as long as the result is unambiguous 

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [34]:
z = np.arange(3).reshape(3, 1)
print(z)

[[0]
 [1]
 [2]]


In [35]:
print(z + Y)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
