In [1]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])

In [3]:
print(x)
print(type(x))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [4]:
x.dtype

dtype('int64')

In [5]:
x.shape

(5,)

In [12]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(y)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
y.dtype

dtype('int64')

In [14]:
y.shape

(4, 3)

In [15]:
y.size

12

In [16]:
# String type array
x = np.array(['Hello', 'World'])
print(x)

['Hello' 'World']


In [17]:
print('shape', x.shape)
print('type', type(x))
print('dtype: ', x.dtype)

shape (2,)
type <class 'numpy.ndarray'>
dtype:  <U5


In [18]:
x = np.array([1, 2.5, 4])
print(x, x.dtype)

[1.  2.5 4. ] float64


In [19]:
x = np.array([1.5, 2.2, 3.7], dtype=np.int64)
print(x)
print('dtype: ', x.dtype)

[1 2 3]
dtype:  int64


In [22]:
x = np.array([1, 2, 3, 4, 5])
np.save('my_array', x)

In [23]:
x1 = np.load('my_array.npy')
print(x1)

[1 2 3 4 5]
