In [1]:
import numpy as np

###### Types of indexing

1. ndarray[start:end]
2. ndarray[ start]
3. ndarray[end]

In [2]:
X = np.arange(1, 21).reshape(4, 5)
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [37]:
print(X)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [7]:
z = X[1:4, 2:5]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [6]:
z = X[1:, 2:]
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [10]:
z = X[3, :]
print(z)

[16 17 18 19 20]


In [17]:
z = X[:, :]
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [18]:
z = X[:, :4]
print(z)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


In [20]:
z = X[:3, 2:5]
print(z)

[[ 3  4  5]
 [ 8  9 10]
 [13 14 15]]


In [24]:
z = X[:, 2:3]
print(z)



[[ 3]
 [ 8]
 [13]
 [18]]


In [34]:
z = X[1:, 2:]
print(z)


[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [33]:
#slicing only creates a view of the array, but the sliced data is not copied into z
z[2,2] = 20
print(z)

[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [36]:
#using copy won't modify x

#z = np.copy(X[1:, 2:])

# alternatively, use it as a method: 

z = X[1:, 2:].copy()

print(z)


[[ 8  9 10]
 [13 14 15]
 [18 19 20]]


In [31]:
z[2,2] = 555
print(z)

[[  8   9  10]
 [ 13  14  15]
 [ 18  19 555]]


In [39]:
X = np.arange(20).reshape(4, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [38]:
#slicing with indices

indices = np.array([1, 3])
print(indices)

[1 3]


In [41]:
y = X[indices, :]
print(y)

[[ 5  6  7  8  9]
 [15 16 17 18 19]]


In [42]:
z = X[:, indices]
print(z)

[[ 1  3]
 [ 6  8]
 [11 13]
 [16 18]]


In [43]:
z = np.diag(X)
print(z)

[ 0  6 12 18]


In [44]:
z = np.diag(X, k=1)
print(z)

[ 1  7 13 19]


In [45]:
z = np.diag(X, k=-1)
print(z)

[ 5 11 17]


In [46]:
# unique function
X = np.array([[1, 2, 3], [5, 2, 8], [1, 2, 3]])
print(X)

[[1 2 3]
 [5 2 8]
 [1 2 3]]


In [47]:
print(np.unique(X))

[1 2 3 5 8]
