In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3, 4, 5])
print(x)

[1 2 3 4 5]


In [3]:
print('1st element', x[0])
print('2nd element', x[1])
print('5th element', x[4])

1st element 1
2nd element 2
5th element 5


In [4]:
print('1st element', x[-5])
print('2nd element', x[-4])
print('5th element', x[-1])

1st element 1
2nd element 2
5th element 5


In [5]:
x[3] = 20
print(x)

[ 1  2  3 20  5]


In [33]:
x = np.arange(1, 10).reshape(3, 3)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print('Element at (0, 0)', X[0 ,0])
print('Element at (0, 1)', x[0 ,1])
print('Element at (2, 2)', x[-1, -1])

Element at (0, 0) 1
Element at (0, 1) 2
Element at (2, 2) 9


In [15]:
x[0, 0] = 20
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [47]:
np.delete(x, [1, 2])

array([1, 4, 5, 6, 7, 8, 9])

In [17]:
print(x)

[[20  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [55]:
Y = np.arange(1, 10).reshape(3, 3)
print(Y)

W = np.delete(Y, 0, axis=-1)
print('\n', W)

V = np.delete(Y, [0, 2], axis=1)
print('\n', V)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[2 3]
 [5 6]
 [8 9]]

 [[2]
 [5]
 [8]]


In [54]:
x = np.array([1, 2, 3, 4, 5])
print(x)
x = np.append(x, 6)
print(x)
x = np.append(x, [7, 8])
print(x)

[1 2 3 4 5]
[1 2 3 4 5 6]
[1 2 3 4 5 6 7 8]


In [59]:
y = np.arange(1, 10).reshape(3, 3)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
W = np.append(Y, [[10, 11, 12]], axis=0)
print(W)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [65]:
V = np.append(Y, [[10], [11], [12]], axis=1)
print(V)

[[ 1  2  3 10]
 [ 4  5  6 11]
 [ 7  8  9 12]]


In [66]:
x = np.array([1, 2, 5, 6, 7])
print(x)

[1 2 5 6 7]


In [67]:
x = np.insert(x, 2, [3, 4])
print(x)

[1 2 3 4 5 6 7]


In [68]:
Y = np.array([[1, 2, 3], [7, 8, 9]])
print(Y)

[[1 2 3]
 [7 8 9]]


In [72]:
W = np.insert(Y, 1, [4, 5, 6], axis=0)
print(W)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [73]:
V = np.insert(Y, 1, 5, axis=1)
print(V)

[[1 5 2 3]
 [7 5 8 9]]


In [74]:
# Stacking

x = np.array([1, 2])
print(x)

[1 2]


In [75]:
Y = np.array([[3, 4], [5, 6]])
print(Y)

[[3 4]
 [5 6]]


In [79]:
z = np.vstack((x, Y))
print(z)

[[1 2]
 [3 4]
 [5 6]]


In [84]:
# In order to use horizontal stack (hstack), the x vector must be reshaped to match the 2, 1 shape of Y

reshaped = x.reshape(2, 1)
print(reshaped)
w = np.hstack((Y, reshaped))
print(w)

[[1]
 [2]]
[[3 4 1]
 [5 6 2]]
