In [1]:
import numpy as np

In [13]:
X = np.arange(25).reshape(5, 5)
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
z = X[X > 10]
print(z)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [4]:
z = X[X <= 7]
print(z)

[0 1 2 3 4 5 6 7]


In [11]:
z = X[(X > 10) & (X < 17)]
print(z)

[]


In [16]:
X[(X > 10) & (X < 17)] = -1
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]
 [20 21 22 23 24]]


In [18]:
# Set operations

x = np.array([1, 2, 3, 4, 5])
y = np.array([6, 7, 3, 8, 4])

print(np.intersect1d(x, y))
print(np.setdiff1d(x, y))
print(np.union1d(x, y))

[3 4]
[1 2 5]
[1 2 3 4 5 6 7 8]


In [20]:
x = np.random.randint(1, 11, size=(10, ))
print(x)

[1 2 6 6 7 2 5 2 9 6]


In [24]:
print(np.sort(x))
# np.sort sorts x out of place and leave it as is
print(x)
# whilst x.sort modifies x
x.sort()
print(x)


[1 2 2 2 5 6 6 6 7 9]
[1 2 6 6 7 2 5 2 9 6]
[1 2 2 2 5 6 6 6 7 9]


In [23]:
# sort and combine unique values
print(np.sort(np.unique(x)))

[1 2 5 6 7 9]


In [25]:
x = np.random.randint(1, 11, size=(5,5 ))
print(x)

[[ 5  7 10  6  3]
 [ 3  4  9  9  2]
 [ 2 10  6  2  5]
 [ 3  1  1  7  9]
 [10  6  9  6  9]]


In [30]:
# sorting by row
z = np.sort(x, axis = 1)
print(z)

#sorting by column
z = np.sort(x, axis = 0)
print('\n', z)

[[ 3  5  6  7 10]
 [ 2  3  4  9  9]
 [ 2  2  5  6 10]
 [ 1  1  3  7  9]
 [ 6  6  9  9 10]]

 [[ 2  1  1  2  2]
 [ 3  4  6  6  3]
 [ 3  6  9  6  5]
 [ 5  7  9  7  9]
 [10 10 10  9  9]]


In [ ]:
# QUIZ 
# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
# Afterwards use Boolean indexing to pick out only the odd numbers in the array

# Create a 5 x 5 ndarray with consecutive integers from 1 to 25 (inclusive).
X = np.arange(1, 26).reshape(5, 5)

print(X)

# Use Boolean indexing to pick out only the odd numbers in the array
Y = X[X % 2 != 0]

print(Y)
